### ISSUE TITLE
multiple destinations / random conductor

### ISSUE THREAD

**Issue by ashlinrichardson** [ecsendmail/MultiverseContagion#27]
Extend operation of conductor to add stochastic element.. 
.. variable destination!

**Comment by ashlinrichardson** [comment]
@ecsendmail please try making a comment here

**Comment by MahdiHajiabadi** [comment]
Hi @ashlinrichardson 
It's going to be a nice extension.

**Comment by ecsendmail** [comment]
OK I get it....**so be it**
